
package departmentdetailsservice.client;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "DepartmentFinderService", targetNamespace = "http://departmentdetailsservice/", wsdlLocation = "http://localhost/wsdl/DepartmentFinder.wsdl")
public class DepartmentFinderService
    extends Service
{

    private final static URL DEPARTMENTFINDERSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(departmentdetailsservice.client.DepartmentFinderService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = departmentdetailsservice.client.DepartmentFinderService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost/wsdl/DepartmentFinder.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost/wsdl/DepartmentFinder.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        DEPARTMENTFINDERSERVICE_WSDL_LOCATION = url;
    }

    public DepartmentFinderService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DepartmentFinderService() {
        super(DEPARTMENTFINDERSERVICE_WSDL_LOCATION, new QName("http://departmentdetailsservice/", "DepartmentFinderService"));
    }

    /**
     * 
     * @return
     *     returns DepartmentFinder
     */
    @WebEndpoint(name = "DepartmentFinderPort")
    public DepartmentFinder getDepartmentFinderPort() {
        return super.getPort(new QName("http://departmentdetailsservice/", "DepartmentFinderPort"), DepartmentFinder.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DepartmentFinder
     */
    @WebEndpoint(name = "DepartmentFinderPort")
    public DepartmentFinder getDepartmentFinderPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://departmentdetailsservice/", "DepartmentFinderPort"), DepartmentFinder.class, features);
    }

    /**
     * 
     * @return
     *     returns DepartmentFinderResponse
     */
    @WebEndpoint(name = "DepartmentFinderCallbackPort")
    public DepartmentFinderResponse getDepartmentFinderCallbackPort() {
        return super.getPort(new QName("http://departmentdetailsservice/", "DepartmentFinderCallbackPort"), DepartmentFinderResponse.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DepartmentFinderResponse
     */
    @WebEndpoint(name = "DepartmentFinderCallbackPort")
    public DepartmentFinderResponse getDepartmentFinderCallbackPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://departmentdetailsservice/", "DepartmentFinderCallbackPort"), DepartmentFinderResponse.class, features);
    }

}
