
package departmentdetailsservice.client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "DepartmentFinder", targetNamespace = "http://departmentdetailsservice/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DepartmentFinder {


    /**
     * 
     * @param deptNumber
     * @return
     *     returns departmentdetailsservice.client.DepartmentDetails
     * @throws DepartmentFinderFault
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDepartmentDetails", targetNamespace = "http://departmentdetailsservice/", className = "departmentdetailsservice.client.GetDepartmentDetails")
    @ResponseWrapper(localName = "getDepartmentDetailsResponse", targetNamespace = "http://departmentdetailsservice/", className = "departmentdetailsservice.client.GetDepartmentDetailsResponse")
    public DepartmentDetails getDepartmentDetails(
        @WebParam(name = "deptNumber", targetNamespace = "")
        String deptNumber)
        throws DepartmentFinderFault
    ;

    /**
     * 
     * @param mgrEmailId
     * @throws DepartmentFinderFault
     */
    @WebMethod
    @RequestWrapper(localName = "getDepartmentByMgrEmailId", targetNamespace = "http://departmentdetailsservice/", className = "departmentdetailsservice.client.GetDepartmentByMgrEmailId")
    @ResponseWrapper(localName = "getDepartmentByMgrEmailIdResponse", targetNamespace = "http://departmentdetailsservice/", className = "departmentdetailsservice.client.GetDepartmentByMgrEmailIdResponse")
    public void getDepartmentByMgrEmailId(
        @WebParam(name = "mgrEmailId", targetNamespace = "")
        String mgrEmailId)
        throws DepartmentFinderFault
    ;

    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDepartments", targetNamespace = "http://departmentdetailsservice/", className = "departmentdetailsservice.client.GetDepartments")
    @ResponseWrapper(localName = "getDepartmentsResponse", targetNamespace = "http://departmentdetailsservice/", className = "departmentdetailsservice.client.GetDepartmentsResponse")
    public List<String> getDepartments();

}
